export const FONT_OPTIONS = [
  "Arial",
  "Arial Black",
  "Arial Narrow",
  "Calibri",
  "Cambria",
  "Candara",
  "Century Gothic",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Corbel",
  "Courier New",
  "Georgia",
  "Helvetica",
  "Impact",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Palatino Linotype",
  "Segoe UI",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
  "Aptos",
  "Aptos Display",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Raleway",
  "Nunito",
  "Nunito Sans",
  "Inter",
  "Oswald",
  "Merriweather",
  "Playfair Display",
  "Bebas Neue",
  "Ubuntu",
  "Rubik",
  "Mulish",
  "Quicksand",
  "Work Sans",
  "Manrope",
  "Karla",
  "Barlow",
  "Barlow Condensed",
  "DM Sans",
  "DM Serif Display",
  "Fira Sans",
  "Fira Code",
  "Source Sans 3",
  "Source Serif 4",
  "PT Sans",
  "PT Serif",
  "Noto Sans",
  "Noto Serif",
  "Noto Sans Display",
  "Libre Baskerville",
  "Libre Franklin",
  "Josefin Sans",
  "Josefin Slab",
  "Archivo",
  "Archivo Black",
  "Arimo",
  "Cabin",
  "Crimson Text",
  "Exo 2",
  "Fjalla One",
  "Heebo",
  "Hind",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Inconsolata",
  "Kanit",
  "Lexend",
  "Lora",
  "Maven Pro",
  "Mukta",
  "Overpass",
  "Oxygen",
  "Prompt",
  "Public Sans",
  "Roboto Condensed",
  "Roboto Slab",
  "Signika",
  "Titillium Web",
  "Varela Round",
  "Yanone Kaffeesatz",
  "Zilla Slab",
  "Abril Fatface",
  "Acme",
  "Alfa Slab One",
  "Amatic SC",
  "Anton",
  "Baloo 2",
  "Bangers",
  "Caveat",
  "Comfortaa",
  "Cormorant Garamond",
  "Dancing Script",
  "Domine",
  "EB Garamond",
  "Fredoka",
  "Great Vibes",
  "Indie Flower",
  "Kalam",
  "Lobster",
  "Lobster Two",
  "Merriweather Sans",
  "Pacifico",
  "Patrick Hand",
  "Permanent Marker",
  "Righteous",
  "Sacramento",
  "Shadows Into Light",
  "Sora",
  "Space Grotesk",
  "Teko",
  "Urbanist",
];

export function loadWebFont(name) {
  if (
    !name ||
    document.querySelector(`link[data-jenius-font="${CSS.escape(name)}"]`)
  )
    return;
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.dataset.jeniusFont = name;
  link.href = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(name).replace(/%20/g, "+")}:ital,wght@0,300;0,400;0,600;0,700;0,800;1,400;1,700&display=swap`;
  document.head.appendChild(link);
}

export function textStyle(style = {}, fallbackColor = "#ffffff") {
  const result = {
    fontFamily: `"${style.fontFamily || "Arial"}",sans-serif`,
    fontSize: `${style.fontSize || 32}px`,
    fontWeight: style.bold ? 700 : style.fontWeight || 400,
    fontStyle: style.italic ? "italic" : "normal",
    textDecoration: style.underline ? "underline" : "none",
    textAlign: style.align || "left",
    lineHeight: style.lineHeight || 1.2,
    letterSpacing: `${style.letterSpacing || 0}px`,
    textTransform: style.textTransform || "none",
  };
  if (style.gradientEnabled) {
    result.backgroundImage = `linear-gradient(${style.gradientAngle || 90}deg,${style.gradientFrom || "#f97316"},${style.gradientTo || "#facc15"})`;
    result.backgroundClip = "text";
    result.WebkitBackgroundClip = "text";
    result.color = "transparent";
  } else result.color = style.color || fallbackColor;
  return result;
}
