import { useEffect, useState } from "react";
import { Archive, BookOpen, Check, Copy, Edit3, Eye, FolderOpen, Share2, Trash2, Users } from "lucide-react";
import OpeningLogin from "./components/auth/OpeningLogin";
import Sidebar from "./components/layout/Sidebar";
import Topbar from "./components/layout/Topbar";
import StudentPlayer from "./components/student/StudentPlayer";
import MaterialBuilder from "./components/materials/MaterialBuilder";
const STORAGE_KEY="jeniusppt-v3";const defaultState={materials:[],participants:[]};
const blankMaterial=()=>({id:crypto.randomUUID(),title:"Materi Baru",subject:"Ekonomi",className:"XI IPS",status:"Draft",shareCode:`JP-${Math.random().toString(36).slice(2,7).toUpperCase()}`,activeSlide:0,activeQuestion:0,slides:[{title:"Judul Materi",body:"Tulis isi materi di sini.",background:{type:"css",value:"linear-gradient(135deg,#0b1f46,#1d4ed8)"}}],questions:[{type:"pg",question:"Contoh pertanyaan pilihan ganda?",options:["A","B","C","D"],answer:0,timer:15,points:1000},{type:"truefalse",question:"Contoh soal benar atau salah.",answer:true,timer:15,points:1000}]});
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||defaultState}catch{return defaultState}}
export default function App(){if(window.location.pathname.startsWith("/play/"))return <StudentPlayer/>;const[user,setUser]=useState(null);const[page,setPage]=useState("dashboard");const[state,setState]=useState(loadState);const[toast,setToast]=useState("");const[editingId,setEditingId]=useState(null);useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state)),[state]);const editingMaterial=state.materials.find(m=>m.id===editingId);function notify(t){setToast(t);setTimeout(()=>setToast(""),2200)}function updateMaterial(id,patch){setState(old=>({...old,materials:old.materials.map(m=>m.id===id?{...m,...patch}:m)}))}function createMaterial(){const item=blankMaterial();setState(old=>({...old,materials:[item,...old.materials]}));setEditingId(item.id);notify("Materi baru dibuat.")}function publishMaterial(material){localStorage.setItem(`jeniusppt_package_${material.shareCode}`,JSON.stringify(material));updateMaterial(material.id,{status:"Published"});notify("Materi berhasil dipublish.")}function duplicateMaterial(material){setState(old=>({...old,materials:[{...material,id:crypto.randomUUID(),title:material.title+" Copy",status:"Draft",shareCode:`JP-${Math.random().toString(36).slice(2,7).toUpperCase()}`},...old.materials]}));notify("Materi berhasil dicopy.")}function deleteMaterial(material){setState(old=>({...old,materials:old.materials.filter(m=>m.id!==material.id)}));notify("Materi dihapus.")}if(!user)return <OpeningLogin onLogin={setUser}/>;if(editingMaterial)return <div className="app-shell"><Sidebar user={user} page="materials" setPage={setPage} onLogout={()=>setUser(null)}/><main className="main-area">{toast&&<div className="toast"><Check size={18}/>{toast}</div>}<MaterialBuilder material={editingMaterial} updateMaterial={updateMaterial} publishMaterial={publishMaterial} onBack={()=>setEditingId(null)}/></main></div>;const title=page==="dashboard"?"Dashboard":page==="materials"?"Materi":page==="participants"?"Peserta":"JeniusPPT";return <div className="app-shell">{toast&&<div className="toast"><Check size={18}/>{toast}</div>}<Sidebar user={user} page={page} setPage={setPage} onLogout={()=>setUser(null)}/><main className="main-area"><Topbar title={title} user={user} onCreate={createMaterial}/>{page==="dashboard"&&<Dashboard state={state} onCreate={createMaterial}/>} {page==="materials"&&<Materials materials={state.materials} publishMaterial={publishMaterial} duplicateMaterial={duplicateMaterial} deleteMaterial={deleteMaterial} editMaterial={m=>setEditingId(m.id)}/>} {page==="participants"&&<Participants/>} {!["dashboard","materials","participants"].includes(page)&&<ComingSoon title={title}/>}</main></div>}
function Dashboard({state,onCreate}){const published=state.materials.filter(m=>m.status==="Published").length;return <section className="page"><div className="welcome-card"><div><span className="eyebrow">JeniusPPT v3 Part 2</span><h1>Mulai dari materi, lanjut slide, lanjut kuis, lalu publish.</h1><p>Alur dibuat bertahap supaya guru tidak bingung saat membuat pembelajaran interaktif.</p></div><button className="primary-button" onClick={onCreate}>Buat Materi</button></div><div className="stats-grid"><Stat icon={<BookOpen/>} label="Total Materi" value={state.materials.length}/><Stat icon={<Archive/>} label="Published" value={published}/><Stat icon={<Users/>} label="Peserta" value={state.participants.length}/><Stat icon={<FolderOpen/>} label="Workspace" value="2"/></div><div className="feature-grid"><Feature title="Editor PPT" desc="Slide 16:9, edit langsung, background cerah, upload lokal dan URL."/><Feature title="Quiz Builder" desc="Pilihan ganda dan benar/salah dengan klik jawaban benar."/><Feature title="Preview Lengkap" desc="Guru bisa cek PPT dan kuis sebelum membagikan link."/><Feature title="Share Link" desc="Siswa masuk dari /play/kode, belajar, kuis, lalu nilai."/></div></section>}
function Materials({materials,publishMaterial,duplicateMaterial,deleteMaterial,editMaterial}){return <section className="page"><div className="page-head"><div><span className="eyebrow">Materi</span><h1>Semua Materi</h1><p>Kelola informasi, PPT, kuis, preview, publish, dan share link.</p></div></div>{materials.length===0?<div className="empty-state"><h2>Belum ada materi</h2><p>Klik tombol Buat Materi di kanan atas untuk mulai.</p></div>:<div className="material-grid">{materials.map(m=><article className="material-card" key={m.id}><span className={m.status==="Published"?"badge success":"badge"}>{m.status}</span><h2>{m.title}</h2><p>{m.subject} • {m.className}</p><div className="material-meta"><span>{m.slides.length} Slide</span><span>{m.questions.length} Soal</span><span>{m.shareCode}</span></div><div className="card-actions"><button onClick={()=>editMaterial(m)}><Edit3 size={16}/>Edit</button><button onClick={()=>publishMaterial(m)}><Share2 size={16}/>Publish</button><a href={`/play/${m.shareCode}`} target="_blank"><Eye size={16}/>Preview</a><button onClick={()=>duplicateMaterial(m)}><Copy size={16}/>Copy</button><button className="danger" onClick={()=>deleteMaterial(m)}><Trash2 size={16}/>Hapus</button></div></article>)}</div>}</section>}
function Participants(){return <section className="page"><div className="empty-state"><h2>Peserta realtime masuk Part 3</h2><p>Setelah Firestore disambungkan, guru bisa melihat nama, kelas, progres, benar, salah, dan nilai.</p></div></section>}
function ComingSoon({title}){return <section className="page"><div className="empty-state"><h2>{title} sedang disiapkan</h2><p>Modul ini masuk ke part berikutnya.</p></div></section>}
function Stat({icon,label,value}){return <div className="stat-card"><div>{icon}</div><p>{label}</p><h2>{value}</h2></div>}
function Feature({title,desc}){return <div className="feature-card"><h3>{title}</h3><p>{desc}</p></div>}
